export const ProjectItems = [
  {
    id: 1,
    img: "./project1.png",
    title: "Pickles",
    about: "An e-commerce website built with the Django Framework.",
    liveURL: "https://pickles-eshop.herokuapp.com/",
    repoURL: "https://github.com/Johnny-Morgan/pickles",
    technologies: [
      "./python.png",
      "./django.png",
      "./postgresql.png",
      "./aws.png",
      "./heroku.png",
    ],
  },
  {
    id: 2,
    img: "./project2.png",
    title: "Hike Logger",
    about: "The perfect place to log and share your hikes.",
    liveURL: "https://hike-logger.herokuapp.com/",
    repoURL: "https://github.com/Johnny-Morgan/hike-logger",
    technologies: [
      "./python.png",
      "./flask.png",
      "./mongodb.png",
      "./heroku.png",
    ],
  },
  {
    id: 3,
    img: "./project3.png",
    title: "Memory Blocks",
    about: "A fun and challenging memory game.",
    liveURL: "https://johnny-morgan.github.io/memory-blocks/",
    repoURL: "https://github.com/Johnny-Morgan/memory-blocks",
    technologies: ["./javascript.png", "./jquery.png"],
  },
];
